tasks:
  - init: |
      yarn install &&
      # as we can't tell the installer not to start a dev server, let's kill it afterward
      echo 'yarn installer:ci && rm script.sh && kill -9 -"$$"' > script.sh && bash script.sh
    command: yarn run dev

ports:
  - port: 3000
    onOpen: open-preview

vscode:
  extensions:
    - octref.vetur@0.23.0:TEzauMObB6f3i2JqlvrOpA==
    - dbaeumer.vscode-eslint@2.0.15:/v3eRFwBI38JLZJv5ExY5g==
    - eg2.vscode-npm-script@0.3.11:peDPJqeL8FmmJiabU4fAJQ==
    - formulahendry.auto-close-tag@0.5.6:oZ/8R2VhZEhkHsoeO57hSw==
    - formulahendry.auto-rename-tag@0.1.1:lKCmLIZAiCM0M8AjDnwCLQ==
    - dariofuzinato.vue-peek@1.0.2:oYJg0oZA/6FBnFfW599HRg==
